# Name of the Workflow
name: Build and Deploy

# Triggers for the Workflow
on:
  push:
    branches:
      - dev       # Trigger on pushes to the 'dev' branch
      - uat       # Trigger on pushes to the 'uat' branch
  workflow_dispatch:  # Manual trigger for on-demand runs

permissions:
      id-token: write
      contents: read

# Global Environment Variables
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Path to the Azure Function app package
  DOTNET_VERSION: '8.0.x'              # .NET version to use for build and deployment

# Job Definition
jobs:
  build-and-deploy:
    name: Build and Deploy to Azure Function App
    runs-on: windows-latest  # Use a Windows runner for compatibility with Azure Functions

    # Define Environment Based on Branch
    environment:
      name: ${{ github.ref == 'refs/heads/dev' && 'Develop' || github.ref == 'refs/heads/uat' && 'UAT' }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Step 1: Checkout Repository
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Azure Auth'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 2: Setup .NET Environment
      - name: 'Setup .NET Environment'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Step 3: Build Application
      - name: 'Build Azure Function App'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      # Step 4: Deploy to Azure Functions
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-webapp
        with:
          app-name: '${{ secrets.AZURE_WEBAPP_NAME }}'  # Use environment secret for app name
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          
      # Step 5: Post-Deployment Verification
      - name: 'Verify Deployment'
        run: |
          echo "Deployment completed to ${{ secrets.AZURE_WEBAPP_NAME }} in the ${{ github.ref == 'refs/heads/dev' && 'Develop' || github.ref == 'refs/heads/uat' && 'UAT' }} environment."
