name: Build and Deploy

on:
  push:
    branches:
      - dev
      - uat
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: ${{ github.ref == 'refs/heads/dev' && 'Develop' || github.ref == 'refs/heads/uat' && 'UAT' }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    env:
      AZURE_WEBAPP_NAME: ${{ github.ref == 'refs/heads/dev' && 'myFunction-dev-01' || github.ref == 'refs/heads/uat' && 'myFunction-uat-01' }}
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: deploy-to-webapp
        with:
          app-name: '${{ env.AZURE_WEBAPP_NAME }}'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
